// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnna,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=13129,HLS_SYN_TPT=none,HLS_SYN_MEM=46,HLS_SYN_DSP=3,HLS_SYN_FF=5915,HLS_SYN_LUT=6833,HLS_VERSION=2018_3}" *)

module cnna (
        ap_clk,
        ap_rst_n,
        m_axi_WEIGHTS_DDR_AWVALID,
        m_axi_WEIGHTS_DDR_AWREADY,
        m_axi_WEIGHTS_DDR_AWADDR,
        m_axi_WEIGHTS_DDR_AWID,
        m_axi_WEIGHTS_DDR_AWLEN,
        m_axi_WEIGHTS_DDR_AWSIZE,
        m_axi_WEIGHTS_DDR_AWBURST,
        m_axi_WEIGHTS_DDR_AWLOCK,
        m_axi_WEIGHTS_DDR_AWCACHE,
        m_axi_WEIGHTS_DDR_AWPROT,
        m_axi_WEIGHTS_DDR_AWQOS,
        m_axi_WEIGHTS_DDR_AWREGION,
        m_axi_WEIGHTS_DDR_AWUSER,
        m_axi_WEIGHTS_DDR_WVALID,
        m_axi_WEIGHTS_DDR_WREADY,
        m_axi_WEIGHTS_DDR_WDATA,
        m_axi_WEIGHTS_DDR_WSTRB,
        m_axi_WEIGHTS_DDR_WLAST,
        m_axi_WEIGHTS_DDR_WID,
        m_axi_WEIGHTS_DDR_WUSER,
        m_axi_WEIGHTS_DDR_ARVALID,
        m_axi_WEIGHTS_DDR_ARREADY,
        m_axi_WEIGHTS_DDR_ARADDR,
        m_axi_WEIGHTS_DDR_ARID,
        m_axi_WEIGHTS_DDR_ARLEN,
        m_axi_WEIGHTS_DDR_ARSIZE,
        m_axi_WEIGHTS_DDR_ARBURST,
        m_axi_WEIGHTS_DDR_ARLOCK,
        m_axi_WEIGHTS_DDR_ARCACHE,
        m_axi_WEIGHTS_DDR_ARPROT,
        m_axi_WEIGHTS_DDR_ARQOS,
        m_axi_WEIGHTS_DDR_ARREGION,
        m_axi_WEIGHTS_DDR_ARUSER,
        m_axi_WEIGHTS_DDR_RVALID,
        m_axi_WEIGHTS_DDR_RREADY,
        m_axi_WEIGHTS_DDR_RDATA,
        m_axi_WEIGHTS_DDR_RLAST,
        m_axi_WEIGHTS_DDR_RID,
        m_axi_WEIGHTS_DDR_RUSER,
        m_axi_WEIGHTS_DDR_RRESP,
        m_axi_WEIGHTS_DDR_BVALID,
        m_axi_WEIGHTS_DDR_BREADY,
        m_axi_WEIGHTS_DDR_BRESP,
        m_axi_WEIGHTS_DDR_BID,
        m_axi_WEIGHTS_DDR_BUSER,
        m_axi_FIN_DDR_AWVALID,
        m_axi_FIN_DDR_AWREADY,
        m_axi_FIN_DDR_AWADDR,
        m_axi_FIN_DDR_AWID,
        m_axi_FIN_DDR_AWLEN,
        m_axi_FIN_DDR_AWSIZE,
        m_axi_FIN_DDR_AWBURST,
        m_axi_FIN_DDR_AWLOCK,
        m_axi_FIN_DDR_AWCACHE,
        m_axi_FIN_DDR_AWPROT,
        m_axi_FIN_DDR_AWQOS,
        m_axi_FIN_DDR_AWREGION,
        m_axi_FIN_DDR_AWUSER,
        m_axi_FIN_DDR_WVALID,
        m_axi_FIN_DDR_WREADY,
        m_axi_FIN_DDR_WDATA,
        m_axi_FIN_DDR_WSTRB,
        m_axi_FIN_DDR_WLAST,
        m_axi_FIN_DDR_WID,
        m_axi_FIN_DDR_WUSER,
        m_axi_FIN_DDR_ARVALID,
        m_axi_FIN_DDR_ARREADY,
        m_axi_FIN_DDR_ARADDR,
        m_axi_FIN_DDR_ARID,
        m_axi_FIN_DDR_ARLEN,
        m_axi_FIN_DDR_ARSIZE,
        m_axi_FIN_DDR_ARBURST,
        m_axi_FIN_DDR_ARLOCK,
        m_axi_FIN_DDR_ARCACHE,
        m_axi_FIN_DDR_ARPROT,
        m_axi_FIN_DDR_ARQOS,
        m_axi_FIN_DDR_ARREGION,
        m_axi_FIN_DDR_ARUSER,
        m_axi_FIN_DDR_RVALID,
        m_axi_FIN_DDR_RREADY,
        m_axi_FIN_DDR_RDATA,
        m_axi_FIN_DDR_RLAST,
        m_axi_FIN_DDR_RID,
        m_axi_FIN_DDR_RUSER,
        m_axi_FIN_DDR_RRESP,
        m_axi_FIN_DDR_BVALID,
        m_axi_FIN_DDR_BREADY,
        m_axi_FIN_DDR_BRESP,
        m_axi_FIN_DDR_BID,
        m_axi_FIN_DDR_BUSER,
        m_axi_FOUT_DDR_AWVALID,
        m_axi_FOUT_DDR_AWREADY,
        m_axi_FOUT_DDR_AWADDR,
        m_axi_FOUT_DDR_AWID,
        m_axi_FOUT_DDR_AWLEN,
        m_axi_FOUT_DDR_AWSIZE,
        m_axi_FOUT_DDR_AWBURST,
        m_axi_FOUT_DDR_AWLOCK,
        m_axi_FOUT_DDR_AWCACHE,
        m_axi_FOUT_DDR_AWPROT,
        m_axi_FOUT_DDR_AWQOS,
        m_axi_FOUT_DDR_AWREGION,
        m_axi_FOUT_DDR_AWUSER,
        m_axi_FOUT_DDR_WVALID,
        m_axi_FOUT_DDR_WREADY,
        m_axi_FOUT_DDR_WDATA,
        m_axi_FOUT_DDR_WSTRB,
        m_axi_FOUT_DDR_WLAST,
        m_axi_FOUT_DDR_WID,
        m_axi_FOUT_DDR_WUSER,
        m_axi_FOUT_DDR_ARVALID,
        m_axi_FOUT_DDR_ARREADY,
        m_axi_FOUT_DDR_ARADDR,
        m_axi_FOUT_DDR_ARID,
        m_axi_FOUT_DDR_ARLEN,
        m_axi_FOUT_DDR_ARSIZE,
        m_axi_FOUT_DDR_ARBURST,
        m_axi_FOUT_DDR_ARLOCK,
        m_axi_FOUT_DDR_ARCACHE,
        m_axi_FOUT_DDR_ARPROT,
        m_axi_FOUT_DDR_ARQOS,
        m_axi_FOUT_DDR_ARREGION,
        m_axi_FOUT_DDR_ARUSER,
        m_axi_FOUT_DDR_RVALID,
        m_axi_FOUT_DDR_RREADY,
        m_axi_FOUT_DDR_RDATA,
        m_axi_FOUT_DDR_RLAST,
        m_axi_FOUT_DDR_RID,
        m_axi_FOUT_DDR_RUSER,
        m_axi_FOUT_DDR_RRESP,
        m_axi_FOUT_DDR_BVALID,
        m_axi_FOUT_DDR_BREADY,
        m_axi_FOUT_DDR_BRESP,
        m_axi_FOUT_DDR_BID,
        m_axi_FOUT_DDR_BUSER,
        s_axi_axilite_AWVALID,
        s_axi_axilite_AWREADY,
        s_axi_axilite_AWADDR,
        s_axi_axilite_WVALID,
        s_axi_axilite_WREADY,
        s_axi_axilite_WDATA,
        s_axi_axilite_WSTRB,
        s_axi_axilite_ARVALID,
        s_axi_axilite_ARREADY,
        s_axi_axilite_ARADDR,
        s_axi_axilite_RVALID,
        s_axi_axilite_RREADY,
        s_axi_axilite_RDATA,
        s_axi_axilite_RRESP,
        s_axi_axilite_BVALID,
        s_axi_axilite_BREADY,
        s_axi_axilite_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_AXILITE_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITE_ADDR_WIDTH = 10;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_WEIGHTS_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_WEIGHTS_DDR_DATA_WIDTH = 128;
parameter    C_M_AXI_WEIGHTS_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_DDR_USER_VALUE = 0;
parameter    C_M_AXI_WEIGHTS_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_WEIGHTS_DDR_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_FIN_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_FIN_DDR_DATA_WIDTH = 128;
parameter    C_M_AXI_FIN_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_FIN_DDR_USER_VALUE = 0;
parameter    C_M_AXI_FIN_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_FIN_DDR_CACHE_VALUE = 3;
parameter    C_M_AXI_FOUT_DDR_ID_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_ADDR_WIDTH = 32;
parameter    C_M_AXI_FOUT_DDR_DATA_WIDTH = 128;
parameter    C_M_AXI_FOUT_DDR_AWUSER_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_ARUSER_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_WUSER_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_RUSER_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_BUSER_WIDTH = 1;
parameter    C_M_AXI_FOUT_DDR_USER_VALUE = 0;
parameter    C_M_AXI_FOUT_DDR_PROT_VALUE = 0;
parameter    C_M_AXI_FOUT_DDR_CACHE_VALUE = 3;

parameter C_S_AXI_AXILITE_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WEIGHTS_DDR_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_FIN_DDR_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_FOUT_DDR_WSTRB_WIDTH = (128 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_WEIGHTS_DDR_AWVALID;
input   m_axi_WEIGHTS_DDR_AWREADY;
output  [C_M_AXI_WEIGHTS_DDR_ADDR_WIDTH - 1:0] m_axi_WEIGHTS_DDR_AWADDR;
output  [C_M_AXI_WEIGHTS_DDR_ID_WIDTH - 1:0] m_axi_WEIGHTS_DDR_AWID;
output  [7:0] m_axi_WEIGHTS_DDR_AWLEN;
output  [2:0] m_axi_WEIGHTS_DDR_AWSIZE;
output  [1:0] m_axi_WEIGHTS_DDR_AWBURST;
output  [1:0] m_axi_WEIGHTS_DDR_AWLOCK;
output  [3:0] m_axi_WEIGHTS_DDR_AWCACHE;
output  [2:0] m_axi_WEIGHTS_DDR_AWPROT;
output  [3:0] m_axi_WEIGHTS_DDR_AWQOS;
output  [3:0] m_axi_WEIGHTS_DDR_AWREGION;
output  [C_M_AXI_WEIGHTS_DDR_AWUSER_WIDTH - 1:0] m_axi_WEIGHTS_DDR_AWUSER;
output   m_axi_WEIGHTS_DDR_WVALID;
input   m_axi_WEIGHTS_DDR_WREADY;
output  [C_M_AXI_WEIGHTS_DDR_DATA_WIDTH - 1:0] m_axi_WEIGHTS_DDR_WDATA;
output  [C_M_AXI_WEIGHTS_DDR_WSTRB_WIDTH - 1:0] m_axi_WEIGHTS_DDR_WSTRB;
output   m_axi_WEIGHTS_DDR_WLAST;
output  [C_M_AXI_WEIGHTS_DDR_ID_WIDTH - 1:0] m_axi_WEIGHTS_DDR_WID;
output  [C_M_AXI_WEIGHTS_DDR_WUSER_WIDTH - 1:0] m_axi_WEIGHTS_DDR_WUSER;
output   m_axi_WEIGHTS_DDR_ARVALID;
input   m_axi_WEIGHTS_DDR_ARREADY;
output  [C_M_AXI_WEIGHTS_DDR_ADDR_WIDTH - 1:0] m_axi_WEIGHTS_DDR_ARADDR;
output  [C_M_AXI_WEIGHTS_DDR_ID_WIDTH - 1:0] m_axi_WEIGHTS_DDR_ARID;
output  [7:0] m_axi_WEIGHTS_DDR_ARLEN;
output  [2:0] m_axi_WEIGHTS_DDR_ARSIZE;
output  [1:0] m_axi_WEIGHTS_DDR_ARBURST;
output  [1:0] m_axi_WEIGHTS_DDR_ARLOCK;
output  [3:0] m_axi_WEIGHTS_DDR_ARCACHE;
output  [2:0] m_axi_WEIGHTS_DDR_ARPROT;
output  [3:0] m_axi_WEIGHTS_DDR_ARQOS;
output  [3:0] m_axi_WEIGHTS_DDR_ARREGION;
output  [C_M_AXI_WEIGHTS_DDR_ARUSER_WIDTH - 1:0] m_axi_WEIGHTS_DDR_ARUSER;
input   m_axi_WEIGHTS_DDR_RVALID;
output   m_axi_WEIGHTS_DDR_RREADY;
input  [C_M_AXI_WEIGHTS_DDR_DATA_WIDTH - 1:0] m_axi_WEIGHTS_DDR_RDATA;
input   m_axi_WEIGHTS_DDR_RLAST;
input  [C_M_AXI_WEIGHTS_DDR_ID_WIDTH - 1:0] m_axi_WEIGHTS_DDR_RID;
input  [C_M_AXI_WEIGHTS_DDR_RUSER_WIDTH - 1:0] m_axi_WEIGHTS_DDR_RUSER;
input  [1:0] m_axi_WEIGHTS_DDR_RRESP;
input   m_axi_WEIGHTS_DDR_BVALID;
output   m_axi_WEIGHTS_DDR_BREADY;
input  [1:0] m_axi_WEIGHTS_DDR_BRESP;
input  [C_M_AXI_WEIGHTS_DDR_ID_WIDTH - 1:0] m_axi_WEIGHTS_DDR_BID;
input  [C_M_AXI_WEIGHTS_DDR_BUSER_WIDTH - 1:0] m_axi_WEIGHTS_DDR_BUSER;
output   m_axi_FIN_DDR_AWVALID;
input   m_axi_FIN_DDR_AWREADY;
output  [C_M_AXI_FIN_DDR_ADDR_WIDTH - 1:0] m_axi_FIN_DDR_AWADDR;
output  [C_M_AXI_FIN_DDR_ID_WIDTH - 1:0] m_axi_FIN_DDR_AWID;
output  [7:0] m_axi_FIN_DDR_AWLEN;
output  [2:0] m_axi_FIN_DDR_AWSIZE;
output  [1:0] m_axi_FIN_DDR_AWBURST;
output  [1:0] m_axi_FIN_DDR_AWLOCK;
output  [3:0] m_axi_FIN_DDR_AWCACHE;
output  [2:0] m_axi_FIN_DDR_AWPROT;
output  [3:0] m_axi_FIN_DDR_AWQOS;
output  [3:0] m_axi_FIN_DDR_AWREGION;
output  [C_M_AXI_FIN_DDR_AWUSER_WIDTH - 1:0] m_axi_FIN_DDR_AWUSER;
output   m_axi_FIN_DDR_WVALID;
input   m_axi_FIN_DDR_WREADY;
output  [C_M_AXI_FIN_DDR_DATA_WIDTH - 1:0] m_axi_FIN_DDR_WDATA;
output  [C_M_AXI_FIN_DDR_WSTRB_WIDTH - 1:0] m_axi_FIN_DDR_WSTRB;
output   m_axi_FIN_DDR_WLAST;
output  [C_M_AXI_FIN_DDR_ID_WIDTH - 1:0] m_axi_FIN_DDR_WID;
output  [C_M_AXI_FIN_DDR_WUSER_WIDTH - 1:0] m_axi_FIN_DDR_WUSER;
output   m_axi_FIN_DDR_ARVALID;
input   m_axi_FIN_DDR_ARREADY;
output  [C_M_AXI_FIN_DDR_ADDR_WIDTH - 1:0] m_axi_FIN_DDR_ARADDR;
output  [C_M_AXI_FIN_DDR_ID_WIDTH - 1:0] m_axi_FIN_DDR_ARID;
output  [7:0] m_axi_FIN_DDR_ARLEN;
output  [2:0] m_axi_FIN_DDR_ARSIZE;
output  [1:0] m_axi_FIN_DDR_ARBURST;
output  [1:0] m_axi_FIN_DDR_ARLOCK;
output  [3:0] m_axi_FIN_DDR_ARCACHE;
output  [2:0] m_axi_FIN_DDR_ARPROT;
output  [3:0] m_axi_FIN_DDR_ARQOS;
output  [3:0] m_axi_FIN_DDR_ARREGION;
output  [C_M_AXI_FIN_DDR_ARUSER_WIDTH - 1:0] m_axi_FIN_DDR_ARUSER;
input   m_axi_FIN_DDR_RVALID;
output   m_axi_FIN_DDR_RREADY;
input  [C_M_AXI_FIN_DDR_DATA_WIDTH - 1:0] m_axi_FIN_DDR_RDATA;
input   m_axi_FIN_DDR_RLAST;
input  [C_M_AXI_FIN_DDR_ID_WIDTH - 1:0] m_axi_FIN_DDR_RID;
input  [C_M_AXI_FIN_DDR_RUSER_WIDTH - 1:0] m_axi_FIN_DDR_RUSER;
input  [1:0] m_axi_FIN_DDR_RRESP;
input   m_axi_FIN_DDR_BVALID;
output   m_axi_FIN_DDR_BREADY;
input  [1:0] m_axi_FIN_DDR_BRESP;
input  [C_M_AXI_FIN_DDR_ID_WIDTH - 1:0] m_axi_FIN_DDR_BID;
input  [C_M_AXI_FIN_DDR_BUSER_WIDTH - 1:0] m_axi_FIN_DDR_BUSER;
output   m_axi_FOUT_DDR_AWVALID;
input   m_axi_FOUT_DDR_AWREADY;
output  [C_M_AXI_FOUT_DDR_ADDR_WIDTH - 1:0] m_axi_FOUT_DDR_AWADDR;
output  [C_M_AXI_FOUT_DDR_ID_WIDTH - 1:0] m_axi_FOUT_DDR_AWID;
output  [7:0] m_axi_FOUT_DDR_AWLEN;
output  [2:0] m_axi_FOUT_DDR_AWSIZE;
output  [1:0] m_axi_FOUT_DDR_AWBURST;
output  [1:0] m_axi_FOUT_DDR_AWLOCK;
output  [3:0] m_axi_FOUT_DDR_AWCACHE;
output  [2:0] m_axi_FOUT_DDR_AWPROT;
output  [3:0] m_axi_FOUT_DDR_AWQOS;
output  [3:0] m_axi_FOUT_DDR_AWREGION;
output  [C_M_AXI_FOUT_DDR_AWUSER_WIDTH - 1:0] m_axi_FOUT_DDR_AWUSER;
output   m_axi_FOUT_DDR_WVALID;
input   m_axi_FOUT_DDR_WREADY;
output  [C_M_AXI_FOUT_DDR_DATA_WIDTH - 1:0] m_axi_FOUT_DDR_WDATA;
output  [C_M_AXI_FOUT_DDR_WSTRB_WIDTH - 1:0] m_axi_FOUT_DDR_WSTRB;
output   m_axi_FOUT_DDR_WLAST;
output  [C_M_AXI_FOUT_DDR_ID_WIDTH - 1:0] m_axi_FOUT_DDR_WID;
output  [C_M_AXI_FOUT_DDR_WUSER_WIDTH - 1:0] m_axi_FOUT_DDR_WUSER;
output   m_axi_FOUT_DDR_ARVALID;
input   m_axi_FOUT_DDR_ARREADY;
output  [C_M_AXI_FOUT_DDR_ADDR_WIDTH - 1:0] m_axi_FOUT_DDR_ARADDR;
output  [C_M_AXI_FOUT_DDR_ID_WIDTH - 1:0] m_axi_FOUT_DDR_ARID;
output  [7:0] m_axi_FOUT_DDR_ARLEN;
output  [2:0] m_axi_FOUT_DDR_ARSIZE;
output  [1:0] m_axi_FOUT_DDR_ARBURST;
output  [1:0] m_axi_FOUT_DDR_ARLOCK;
output  [3:0] m_axi_FOUT_DDR_ARCACHE;
output  [2:0] m_axi_FOUT_DDR_ARPROT;
output  [3:0] m_axi_FOUT_DDR_ARQOS;
output  [3:0] m_axi_FOUT_DDR_ARREGION;
output  [C_M_AXI_FOUT_DDR_ARUSER_WIDTH - 1:0] m_axi_FOUT_DDR_ARUSER;
input   m_axi_FOUT_DDR_RVALID;
output   m_axi_FOUT_DDR_RREADY;
input  [C_M_AXI_FOUT_DDR_DATA_WIDTH - 1:0] m_axi_FOUT_DDR_RDATA;
input   m_axi_FOUT_DDR_RLAST;
input  [C_M_AXI_FOUT_DDR_ID_WIDTH - 1:0] m_axi_FOUT_DDR_RID;
input  [C_M_AXI_FOUT_DDR_RUSER_WIDTH - 1:0] m_axi_FOUT_DDR_RUSER;
input  [1:0] m_axi_FOUT_DDR_RRESP;
input   m_axi_FOUT_DDR_BVALID;
output   m_axi_FOUT_DDR_BREADY;
input  [1:0] m_axi_FOUT_DDR_BRESP;
input  [C_M_AXI_FOUT_DDR_ID_WIDTH - 1:0] m_axi_FOUT_DDR_BID;
input  [C_M_AXI_FOUT_DDR_BUSER_WIDTH - 1:0] m_axi_FOUT_DDR_BUSER;
input   s_axi_axilite_AWVALID;
output   s_axi_axilite_AWREADY;
input  [C_S_AXI_AXILITE_ADDR_WIDTH - 1:0] s_axi_axilite_AWADDR;
input   s_axi_axilite_WVALID;
output   s_axi_axilite_WREADY;
input  [C_S_AXI_AXILITE_DATA_WIDTH - 1:0] s_axi_axilite_WDATA;
input  [C_S_AXI_AXILITE_WSTRB_WIDTH - 1:0] s_axi_axilite_WSTRB;
input   s_axi_axilite_ARVALID;
output   s_axi_axilite_ARREADY;
input  [C_S_AXI_AXILITE_ADDR_WIDTH - 1:0] s_axi_axilite_ARADDR;
output   s_axi_axilite_RVALID;
input   s_axi_axilite_RREADY;
output  [C_S_AXI_AXILITE_DATA_WIDTH - 1:0] s_axi_axilite_RDATA;
output  [1:0] s_axi_axilite_RRESP;
output   s_axi_axilite_BVALID;
input   s_axi_axilite_BREADY;
output  [1:0] s_axi_axilite_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] wddr_V;
reg   [31:0] wddr_V_0_data_reg;
reg    wddr_V_0_vld_reg;
reg    wddr_V_0_ack_out;
wire   [31:0] fiddr_V;
reg   [31:0] fiddr_V_0_data_reg;
reg    fiddr_V_0_vld_reg;
reg    fiddr_V_0_ack_out;
wire   [31:0] foddr_V;
reg   [31:0] foddr_V_0_data_reg;
reg    foddr_V_0_vld_reg;
reg    foddr_V_0_ack_out;
wire    layer_enPara_cnvEn;
wire    layer_enPara_poolEn;
wire   [15:0] layer_wPara_curLayerNum;
wire    layer_wPara_layerDivideType;
wire   [10:0] layer_wPara_sublayerNum_V;
wire   [10:0] layer_wPara_sublayerSeq_V;
wire   [1:0] layer_wPara_subLayerFlag;
wire   [39:0] layer_wPara_memAddrWeights_V;
wire   [39:0] layer_wPara_memAddrBias_V;
wire   [39:0] layer_wPara_memAddrScale_V;
wire   [39:0] layer_wPara_memAddrMean_V;
wire   [39:0] layer_wPara_memAddrVariance_V;
wire   [18:0] layer_wPara_compressionSize_V;
wire   [15:0] layer_wParaNext_curLayerNum;
wire    layer_wParaNext_layerDivideType;
wire   [10:0] layer_wParaNext_sublayerNum_V;
wire   [10:0] layer_wParaNext_sublayerSeq_V;
wire   [1:0] layer_wParaNext_subLayerFlag;
wire   [39:0] layer_wParaNext_memAddrWeights_V;
wire   [39:0] layer_wParaNext_memAddrBias_V;
reg   [39:0] layer_wParaNext_memAddrBias_V_0_data_reg;
reg    layer_wParaNext_memAddrBias_V_0_vld_reg;
reg    layer_wParaNext_memAddrBias_V_0_ack_out;
wire   [39:0] layer_wParaNext_memAddrScale_V;
wire   [39:0] layer_wParaNext_memAddrMean_V;
wire   [39:0] layer_wParaNext_memAddrVariance_V;
wire   [18:0] layer_wParaNext_compressionSize_V;
wire   [15:0] layer_iPara_batchSize;
wire   [15:0] layer_iPara_width;
reg   [15:0] layer_iPara_width_0_data_reg;
reg    layer_iPara_width_0_vld_reg;
reg    layer_iPara_width_0_ack_out;
wire   [15:0] layer_iPara_height;
reg   [15:0] layer_iPara_height_0_data_reg;
reg    layer_iPara_height_0_vld_reg;
reg    layer_iPara_height_0_ack_out;
wire   [12:0] layer_iPara_ci_V;
wire   [12:0] layer_iPara_ciAlign_V;
reg   [12:0] layer_iPara_ciAlign_V_0_data_reg;
reg    layer_iPara_ciAlign_V_0_vld_reg;
reg    layer_iPara_ciAlign_V_0_ack_out;
wire   [12:0] layer_iPara_ciGroup_V;
wire   [39:0] layer_iPara_memAddrImgIn_V;
reg   [39:0] layer_iPara_memAddrImgIn_V_0_data_reg;
reg    layer_iPara_memAddrImgIn_V_0_vld_reg;
reg    layer_iPara_memAddrImgIn_V_0_ack_out;
wire   [15:0] layer_iParaNext_batchSize;
wire   [15:0] layer_iParaNext_width;
wire   [15:0] layer_iParaNext_height;
wire   [12:0] layer_iParaNext_ci_V;
wire   [12:0] layer_iParaNext_ciAlign_V;
wire   [12:0] layer_iParaNext_ciGroup_V;
wire   [39:0] layer_iParaNext_memAddrImgIn_V;
wire   [15:0] layer_oPara_batchSize;
wire   [15:0] layer_oPara_width;
wire   [15:0] layer_oPara_height;
wire   [12:0] layer_oPara_co_V;
reg   [12:0] layer_oPara_co_V_0_data_reg;
reg    layer_oPara_co_V_0_vld_reg;
reg    layer_oPara_co_V_0_ack_out;
wire   [12:0] layer_oPara_coAlign_V;
wire   [12:0] layer_oPara_coGroup_V;
wire   [39:0] layer_oPara_memAddrImgOut_V;
reg   [39:0] layer_oPara_memAddrImgOut_V_0_data_reg;
reg    layer_oPara_memAddrImgOut_V_0_vld_reg;
reg    layer_oPara_memAddrImgOut_V_0_ack_out;
wire   [15:0] layer_oParaNext_batchSize;
wire   [15:0] layer_oParaNext_width;
wire   [15:0] layer_oParaNext_height;
wire   [12:0] layer_oParaNext_co_V;
reg   [12:0] layer_oParaNext_co_V_0_data_reg;
reg    layer_oParaNext_co_V_0_vld_reg;
reg    layer_oParaNext_co_V_0_ack_out;
wire   [12:0] layer_oParaNext_coAlign_V;
wire   [12:0] layer_oParaNext_coGroup_V;
wire   [39:0] layer_oParaNext_memAddrImgOut_V;
wire    layer_cnvPara_relu;
wire   [15:0] layer_cnvPara_dilation;
wire   [4:0] layer_cnvPara_pad_h_V;
wire   [4:0] layer_cnvPara_pad_w_V;
wire   [4:0] layer_cnvPara_kernel_h_V;
wire   [4:0] layer_cnvPara_kernel_w_V;
wire   [4:0] layer_cnvPara_stride_h_V;
wire   [4:0] layer_cnvPara_stride_w_V;
wire    layer_cnvParaNext_relu;
wire   [15:0] layer_cnvParaNext_dilation;
wire   [4:0] layer_cnvParaNext_pad_h_V;
wire   [4:0] layer_cnvParaNext_pad_w_V;
wire   [4:0] layer_cnvParaNext_kernel_h_V;
wire   [4:0] layer_cnvParaNext_kernel_w_V;
wire   [4:0] layer_cnvParaNext_stride_h_V;
wire   [4:0] layer_cnvParaNext_stride_w_V;
wire   [15:0] layer_qPara_qM0;
wire   [31:0] layer_qPara_qN;
wire   [31:0] layer_qPara_qZ1;
wire   [15:0] layer_qPara_qZ2;
wire   [31:0] layer_qPara_qZ3;
wire   [4:0] layer_poolPara_pad_h_V;
wire   [4:0] layer_poolPara_pad_w_V;
wire   [4:0] layer_poolPara_kernel_h_V;
wire   [4:0] layer_poolPara_kernel_w_V;
wire   [4:0] layer_poolPara_stride_h_V;
wire   [4:0] layer_poolPara_stride_w_V;
wire    layer_poolPara_pool_type;
reg   [8:0] bbuf0_V_address0;
reg    bbuf0_V_ce0;
reg    bbuf0_V_we0;
wire   [127:0] bbuf0_V_q0;
wire    WEIGHTS_DDR_AWREADY;
wire    WEIGHTS_DDR_WREADY;
reg    WEIGHTS_DDR_ARVALID;
wire    WEIGHTS_DDR_ARREADY;
wire    WEIGHTS_DDR_RVALID;
reg    WEIGHTS_DDR_RREADY;
wire   [127:0] WEIGHTS_DDR_RDATA;
wire    WEIGHTS_DDR_RLAST;
wire   [0:0] WEIGHTS_DDR_RID;
wire   [0:0] WEIGHTS_DDR_RUSER;
wire   [1:0] WEIGHTS_DDR_RRESP;
wire    WEIGHTS_DDR_BVALID;
wire   [1:0] WEIGHTS_DDR_BRESP;
wire   [0:0] WEIGHTS_DDR_BID;
wire   [0:0] WEIGHTS_DDR_BUSER;
wire    FIN_DDR_AWREADY;
wire    FIN_DDR_WREADY;
reg    FIN_DDR_ARVALID;
wire    FIN_DDR_ARREADY;
wire    FIN_DDR_RVALID;
reg    FIN_DDR_RREADY;
wire   [127:0] FIN_DDR_RDATA;
wire    FIN_DDR_RLAST;
wire   [0:0] FIN_DDR_RID;
wire   [0:0] FIN_DDR_RUSER;
wire   [1:0] FIN_DDR_RRESP;
wire    FIN_DDR_BVALID;
wire   [1:0] FIN_DDR_BRESP;
wire   [0:0] FIN_DDR_BID;
wire   [0:0] FIN_DDR_BUSER;
reg    FOUT_DDR_AWVALID;
wire    FOUT_DDR_AWREADY;
reg    FOUT_DDR_WVALID;
wire    FOUT_DDR_WREADY;
wire    FOUT_DDR_ARREADY;
wire    FOUT_DDR_RVALID;
wire   [127:0] FOUT_DDR_RDATA;
wire    FOUT_DDR_RLAST;
wire   [0:0] FOUT_DDR_RID;
wire   [0:0] FOUT_DDR_RUSER;
wire   [1:0] FOUT_DDR_RRESP;
wire    FOUT_DDR_BVALID;
reg    FOUT_DDR_BREADY;
wire   [1:0] FOUT_DDR_BRESP;
wire   [0:0] FOUT_DDR_BID;
wire   [0:0] FOUT_DDR_BUSER;
reg   [27:0] foddr_V5_reg_556;
wire    ap_CS_fsm_state2;
reg   [27:0] fiddr_V3_reg_561;
reg   [27:0] wddr_V1_reg_566;
reg   [15:0] cnnInst_iPara_width_reg_571;
reg   [15:0] cnnInst_iPara_height_reg_576;
reg   [12:0] cnnInst_iPara_ciAlig_reg_581;
reg   [39:0] cnnInst_iPara_memAdd_reg_586;
reg   [39:0] cnnInst_oPara_memAdd_reg_591;
reg   [12:0] cnnInst_oParaNext_co_reg_596;
reg   [39:0] cnnInst_wParaNext_me_reg_601;
reg   [7:0] tmp_3_reg_606;
wire   [12:0] cnnInst_oPara_coAlig_fu_548_p3;
reg   [12:0] cnnInst_oPara_coAlig_reg_611;
wire    ap_CS_fsm_state4;
wire    grp_testAxiProcess_fu_462_ap_start;
wire    grp_testAxiProcess_fu_462_ap_done;
wire    grp_testAxiProcess_fu_462_ap_idle;
wire    grp_testAxiProcess_fu_462_ap_ready;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWVALID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWADDR;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWLEN;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWSIZE;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWBURST;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWLOCK;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWCACHE;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWPROT;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWQOS;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWREGION;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWUSER;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_WVALID;
wire   [127:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_WDATA;
wire   [15:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_WSTRB;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_WLAST;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_WID;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_WUSER;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARVALID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARADDR;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLEN;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARSIZE;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARBURST;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLOCK;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARCACHE;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARPROT;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARQOS;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARREGION;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARUSER;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_RREADY;
wire    grp_testAxiProcess_fu_462_m_axi_fiddr_V_BREADY;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_AWVALID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWADDR;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLEN;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWSIZE;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWBURST;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLOCK;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWCACHE;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWPROT;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWQOS;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWREGION;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_AWUSER;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_WVALID;
wire   [127:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_WDATA;
wire   [15:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_WSTRB;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_WLAST;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_WID;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_WUSER;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_ARVALID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARADDR;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARID;
wire   [31:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARLEN;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARSIZE;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARBURST;
wire   [1:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARLOCK;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARCACHE;
wire   [2:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARPROT;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARQOS;
wire   [3:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARREGION;
wire   [0:0] grp_testAxiProcess_fu_462_m_axi_foddr_V_ARUSER;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_RREADY;
wire    grp_testAxiProcess_fu_462_m_axi_foddr_V_BREADY;
wire   [8:0] grp_testAxiProcess_fu_462_bbuf0_V_address0;
wire    grp_testAxiProcess_fu_462_bbuf0_V_ce0;
wire    grp_loadBiasFromDRAM_fu_482_ap_start;
wire    grp_loadBiasFromDRAM_fu_482_ap_done;
wire    grp_loadBiasFromDRAM_fu_482_ap_idle;
wire    grp_loadBiasFromDRAM_fu_482_ap_ready;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWVALID;
wire   [31:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWADDR;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWID;
wire   [31:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWLEN;
wire   [2:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWSIZE;
wire   [1:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWBURST;
wire   [1:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWLOCK;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWCACHE;
wire   [2:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWPROT;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWQOS;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWREGION;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWUSER;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WVALID;
wire   [127:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WDATA;
wire   [15:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WSTRB;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WLAST;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WID;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WUSER;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARVALID;
wire   [31:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARADDR;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARID;
wire   [31:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLEN;
wire   [2:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARSIZE;
wire   [1:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARBURST;
wire   [1:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLOCK;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARCACHE;
wire   [2:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARPROT;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARQOS;
wire   [3:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARREGION;
wire   [0:0] grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARUSER;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_RREADY;
wire    grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_BREADY;
wire   [8:0] grp_loadBiasFromDRAM_fu_482_bbuf_V_address0;
wire    grp_loadBiasFromDRAM_fu_482_bbuf_V_ce0;
wire    grp_loadBiasFromDRAM_fu_482_bbuf_V_we0;
wire   [127:0] grp_loadBiasFromDRAM_fu_482_bbuf_V_d0;
reg    grp_testAxiProcess_fu_462_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_loadBiasFromDRAM_fu_482_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [13:0] lhs_V_cast_fu_528_p1;
wire   [13:0] ret_V_1_tr_fu_532_p2;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 wddr_V_0_data_reg = 32'd0;
#0 wddr_V_0_vld_reg = 1'b0;
#0 fiddr_V_0_data_reg = 32'd0;
#0 fiddr_V_0_vld_reg = 1'b0;
#0 foddr_V_0_data_reg = 32'd0;
#0 foddr_V_0_vld_reg = 1'b0;
#0 layer_wParaNext_memAddrBias_V_0_data_reg = 40'd0;
#0 layer_wParaNext_memAddrBias_V_0_vld_reg = 1'b0;
#0 layer_iPara_width_0_data_reg = 16'd0;
#0 layer_iPara_width_0_vld_reg = 1'b0;
#0 layer_iPara_height_0_data_reg = 16'd0;
#0 layer_iPara_height_0_vld_reg = 1'b0;
#0 layer_iPara_ciAlign_V_0_data_reg = 13'd0;
#0 layer_iPara_ciAlign_V_0_vld_reg = 1'b0;
#0 layer_iPara_memAddrImgIn_V_0_data_reg = 40'd0;
#0 layer_iPara_memAddrImgIn_V_0_vld_reg = 1'b0;
#0 layer_oPara_co_V_0_data_reg = 13'd0;
#0 layer_oPara_co_V_0_vld_reg = 1'b0;
#0 layer_oPara_memAddrImgOut_V_0_data_reg = 40'd0;
#0 layer_oPara_memAddrImgOut_V_0_vld_reg = 1'b0;
#0 layer_oParaNext_co_V_0_data_reg = 13'd0;
#0 layer_oParaNext_co_V_0_vld_reg = 1'b0;
#0 grp_testAxiProcess_fu_462_ap_start_reg = 1'b0;
#0 grp_loadBiasFromDRAM_fu_482_ap_start_reg = 1'b0;
end

cnna_bbuf0_V #(
    .DataWidth( 128 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
bbuf0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bbuf0_V_address0),
    .ce0(bbuf0_V_ce0),
    .we0(bbuf0_V_we0),
    .d0(grp_loadBiasFromDRAM_fu_482_bbuf_V_d0),
    .q0(bbuf0_V_q0)
);

cnna_axilite_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITE_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITE_DATA_WIDTH ))
cnna_axilite_s_axi_U(
    .AWVALID(s_axi_axilite_AWVALID),
    .AWREADY(s_axi_axilite_AWREADY),
    .AWADDR(s_axi_axilite_AWADDR),
    .WVALID(s_axi_axilite_WVALID),
    .WREADY(s_axi_axilite_WREADY),
    .WDATA(s_axi_axilite_WDATA),
    .WSTRB(s_axi_axilite_WSTRB),
    .ARVALID(s_axi_axilite_ARVALID),
    .ARREADY(s_axi_axilite_ARREADY),
    .ARADDR(s_axi_axilite_ARADDR),
    .RVALID(s_axi_axilite_RVALID),
    .RREADY(s_axi_axilite_RREADY),
    .RDATA(s_axi_axilite_RDATA),
    .RRESP(s_axi_axilite_RRESP),
    .BVALID(s_axi_axilite_BVALID),
    .BREADY(s_axi_axilite_BREADY),
    .BRESP(s_axi_axilite_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .wddr_V(wddr_V),
    .fiddr_V(fiddr_V),
    .foddr_V(foddr_V),
    .layer_enPara_cnvEn(layer_enPara_cnvEn),
    .layer_enPara_poolEn(layer_enPara_poolEn),
    .layer_wPara_curLayerNum(layer_wPara_curLayerNum),
    .layer_wPara_layerDivideType(layer_wPara_layerDivideType),
    .layer_wPara_sublayerNum_V(layer_wPara_sublayerNum_V),
    .layer_wPara_sublayerSeq_V(layer_wPara_sublayerSeq_V),
    .layer_wPara_subLayerFlag(layer_wPara_subLayerFlag),
    .layer_wPara_memAddrWeights_V(layer_wPara_memAddrWeights_V),
    .layer_wPara_memAddrBias_V(layer_wPara_memAddrBias_V),
    .layer_wPara_memAddrScale_V(layer_wPara_memAddrScale_V),
    .layer_wPara_memAddrMean_V(layer_wPara_memAddrMean_V),
    .layer_wPara_memAddrVariance_V(layer_wPara_memAddrVariance_V),
    .layer_wPara_compressionSize_V(layer_wPara_compressionSize_V),
    .layer_wParaNext_curLayerNum(layer_wParaNext_curLayerNum),
    .layer_wParaNext_layerDivideType(layer_wParaNext_layerDivideType),
    .layer_wParaNext_sublayerNum_V(layer_wParaNext_sublayerNum_V),
    .layer_wParaNext_sublayerSeq_V(layer_wParaNext_sublayerSeq_V),
    .layer_wParaNext_subLayerFlag(layer_wParaNext_subLayerFlag),
    .layer_wParaNext_memAddrWeights_V(layer_wParaNext_memAddrWeights_V),
    .layer_wParaNext_memAddrBias_V(layer_wParaNext_memAddrBias_V),
    .layer_wParaNext_memAddrScale_V(layer_wParaNext_memAddrScale_V),
    .layer_wParaNext_memAddrMean_V(layer_wParaNext_memAddrMean_V),
    .layer_wParaNext_memAddrVariance_V(layer_wParaNext_memAddrVariance_V),
    .layer_wParaNext_compressionSize_V(layer_wParaNext_compressionSize_V),
    .layer_iPara_batchSize(layer_iPara_batchSize),
    .layer_iPara_width(layer_iPara_width),
    .layer_iPara_height(layer_iPara_height),
    .layer_iPara_ci_V(layer_iPara_ci_V),
    .layer_iPara_ciAlign_V(layer_iPara_ciAlign_V),
    .layer_iPara_ciGroup_V(layer_iPara_ciGroup_V),
    .layer_iPara_memAddrImgIn_V(layer_iPara_memAddrImgIn_V),
    .layer_iParaNext_batchSize(layer_iParaNext_batchSize),
    .layer_iParaNext_width(layer_iParaNext_width),
    .layer_iParaNext_height(layer_iParaNext_height),
    .layer_iParaNext_ci_V(layer_iParaNext_ci_V),
    .layer_iParaNext_ciAlign_V(layer_iParaNext_ciAlign_V),
    .layer_iParaNext_ciGroup_V(layer_iParaNext_ciGroup_V),
    .layer_iParaNext_memAddrImgIn_V(layer_iParaNext_memAddrImgIn_V),
    .layer_oPara_batchSize(layer_oPara_batchSize),
    .layer_oPara_width(layer_oPara_width),
    .layer_oPara_height(layer_oPara_height),
    .layer_oPara_co_V(layer_oPara_co_V),
    .layer_oPara_coAlign_V(layer_oPara_coAlign_V),
    .layer_oPara_coGroup_V(layer_oPara_coGroup_V),
    .layer_oPara_memAddrImgOut_V(layer_oPara_memAddrImgOut_V),
    .layer_oParaNext_batchSize(layer_oParaNext_batchSize),
    .layer_oParaNext_width(layer_oParaNext_width),
    .layer_oParaNext_height(layer_oParaNext_height),
    .layer_oParaNext_co_V(layer_oParaNext_co_V),
    .layer_oParaNext_coAlign_V(layer_oParaNext_coAlign_V),
    .layer_oParaNext_coGroup_V(layer_oParaNext_coGroup_V),
    .layer_oParaNext_memAddrImgOut_V(layer_oParaNext_memAddrImgOut_V),
    .layer_cnvPara_relu(layer_cnvPara_relu),
    .layer_cnvPara_dilation(layer_cnvPara_dilation),
    .layer_cnvPara_pad_h_V(layer_cnvPara_pad_h_V),
    .layer_cnvPara_pad_w_V(layer_cnvPara_pad_w_V),
    .layer_cnvPara_kernel_h_V(layer_cnvPara_kernel_h_V),
    .layer_cnvPara_kernel_w_V(layer_cnvPara_kernel_w_V),
    .layer_cnvPara_stride_h_V(layer_cnvPara_stride_h_V),
    .layer_cnvPara_stride_w_V(layer_cnvPara_stride_w_V),
    .layer_cnvParaNext_relu(layer_cnvParaNext_relu),
    .layer_cnvParaNext_dilation(layer_cnvParaNext_dilation),
    .layer_cnvParaNext_pad_h_V(layer_cnvParaNext_pad_h_V),
    .layer_cnvParaNext_pad_w_V(layer_cnvParaNext_pad_w_V),
    .layer_cnvParaNext_kernel_h_V(layer_cnvParaNext_kernel_h_V),
    .layer_cnvParaNext_kernel_w_V(layer_cnvParaNext_kernel_w_V),
    .layer_cnvParaNext_stride_h_V(layer_cnvParaNext_stride_h_V),
    .layer_cnvParaNext_stride_w_V(layer_cnvParaNext_stride_w_V),
    .layer_qPara_qM0(layer_qPara_qM0),
    .layer_qPara_qN(layer_qPara_qN),
    .layer_qPara_qZ1(layer_qPara_qZ1),
    .layer_qPara_qZ2(layer_qPara_qZ2),
    .layer_qPara_qZ3(layer_qPara_qZ3),
    .layer_poolPara_pad_h_V(layer_poolPara_pad_h_V),
    .layer_poolPara_pad_w_V(layer_poolPara_pad_w_V),
    .layer_poolPara_kernel_h_V(layer_poolPara_kernel_h_V),
    .layer_poolPara_kernel_w_V(layer_poolPara_kernel_w_V),
    .layer_poolPara_stride_h_V(layer_poolPara_stride_h_V),
    .layer_poolPara_stride_w_V(layer_poolPara_stride_w_V),
    .layer_poolPara_pool_type(layer_poolPara_pool_type)
);

cnna_WEIGHTS_DDR_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 128 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_WEIGHTS_DDR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_WEIGHTS_DDR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_WEIGHTS_DDR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_WEIGHTS_DDR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_WEIGHTS_DDR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_WEIGHTS_DDR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_WEIGHTS_DDR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_WEIGHTS_DDR_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_WEIGHTS_DDR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_WEIGHTS_DDR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_WEIGHTS_DDR_CACHE_VALUE ))
cnna_WEIGHTS_DDR_m_axi_U(
    .AWVALID(m_axi_WEIGHTS_DDR_AWVALID),
    .AWREADY(m_axi_WEIGHTS_DDR_AWREADY),
    .AWADDR(m_axi_WEIGHTS_DDR_AWADDR),
    .AWID(m_axi_WEIGHTS_DDR_AWID),
    .AWLEN(m_axi_WEIGHTS_DDR_AWLEN),
    .AWSIZE(m_axi_WEIGHTS_DDR_AWSIZE),
    .AWBURST(m_axi_WEIGHTS_DDR_AWBURST),
    .AWLOCK(m_axi_WEIGHTS_DDR_AWLOCK),
    .AWCACHE(m_axi_WEIGHTS_DDR_AWCACHE),
    .AWPROT(m_axi_WEIGHTS_DDR_AWPROT),
    .AWQOS(m_axi_WEIGHTS_DDR_AWQOS),
    .AWREGION(m_axi_WEIGHTS_DDR_AWREGION),
    .AWUSER(m_axi_WEIGHTS_DDR_AWUSER),
    .WVALID(m_axi_WEIGHTS_DDR_WVALID),
    .WREADY(m_axi_WEIGHTS_DDR_WREADY),
    .WDATA(m_axi_WEIGHTS_DDR_WDATA),
    .WSTRB(m_axi_WEIGHTS_DDR_WSTRB),
    .WLAST(m_axi_WEIGHTS_DDR_WLAST),
    .WID(m_axi_WEIGHTS_DDR_WID),
    .WUSER(m_axi_WEIGHTS_DDR_WUSER),
    .ARVALID(m_axi_WEIGHTS_DDR_ARVALID),
    .ARREADY(m_axi_WEIGHTS_DDR_ARREADY),
    .ARADDR(m_axi_WEIGHTS_DDR_ARADDR),
    .ARID(m_axi_WEIGHTS_DDR_ARID),
    .ARLEN(m_axi_WEIGHTS_DDR_ARLEN),
    .ARSIZE(m_axi_WEIGHTS_DDR_ARSIZE),
    .ARBURST(m_axi_WEIGHTS_DDR_ARBURST),
    .ARLOCK(m_axi_WEIGHTS_DDR_ARLOCK),
    .ARCACHE(m_axi_WEIGHTS_DDR_ARCACHE),
    .ARPROT(m_axi_WEIGHTS_DDR_ARPROT),
    .ARQOS(m_axi_WEIGHTS_DDR_ARQOS),
    .ARREGION(m_axi_WEIGHTS_DDR_ARREGION),
    .ARUSER(m_axi_WEIGHTS_DDR_ARUSER),
    .RVALID(m_axi_WEIGHTS_DDR_RVALID),
    .RREADY(m_axi_WEIGHTS_DDR_RREADY),
    .RDATA(m_axi_WEIGHTS_DDR_RDATA),
    .RLAST(m_axi_WEIGHTS_DDR_RLAST),
    .RID(m_axi_WEIGHTS_DDR_RID),
    .RUSER(m_axi_WEIGHTS_DDR_RUSER),
    .RRESP(m_axi_WEIGHTS_DDR_RRESP),
    .BVALID(m_axi_WEIGHTS_DDR_BVALID),
    .BREADY(m_axi_WEIGHTS_DDR_BREADY),
    .BRESP(m_axi_WEIGHTS_DDR_BRESP),
    .BID(m_axi_WEIGHTS_DDR_BID),
    .BUSER(m_axi_WEIGHTS_DDR_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(WEIGHTS_DDR_ARVALID),
    .I_ARREADY(WEIGHTS_DDR_ARREADY),
    .I_ARADDR(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARADDR),
    .I_ARID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARID),
    .I_ARLEN(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLEN),
    .I_ARSIZE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARSIZE),
    .I_ARLOCK(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLOCK),
    .I_ARCACHE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARCACHE),
    .I_ARQOS(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARQOS),
    .I_ARPROT(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARPROT),
    .I_ARUSER(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARUSER),
    .I_ARBURST(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARBURST),
    .I_ARREGION(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARREGION),
    .I_RVALID(WEIGHTS_DDR_RVALID),
    .I_RREADY(WEIGHTS_DDR_RREADY),
    .I_RDATA(WEIGHTS_DDR_RDATA),
    .I_RID(WEIGHTS_DDR_RID),
    .I_RUSER(WEIGHTS_DDR_RUSER),
    .I_RRESP(WEIGHTS_DDR_RRESP),
    .I_RLAST(WEIGHTS_DDR_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(WEIGHTS_DDR_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(WEIGHTS_DDR_WREADY),
    .I_WDATA(128'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(16'd0),
    .I_BVALID(WEIGHTS_DDR_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(WEIGHTS_DDR_BRESP),
    .I_BID(WEIGHTS_DDR_BID),
    .I_BUSER(WEIGHTS_DDR_BUSER)
);

cnna_FIN_DDR_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 128 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FIN_DDR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FIN_DDR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FIN_DDR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FIN_DDR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FIN_DDR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FIN_DDR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FIN_DDR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FIN_DDR_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FIN_DDR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FIN_DDR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FIN_DDR_CACHE_VALUE ))
cnna_FIN_DDR_m_axi_U(
    .AWVALID(m_axi_FIN_DDR_AWVALID),
    .AWREADY(m_axi_FIN_DDR_AWREADY),
    .AWADDR(m_axi_FIN_DDR_AWADDR),
    .AWID(m_axi_FIN_DDR_AWID),
    .AWLEN(m_axi_FIN_DDR_AWLEN),
    .AWSIZE(m_axi_FIN_DDR_AWSIZE),
    .AWBURST(m_axi_FIN_DDR_AWBURST),
    .AWLOCK(m_axi_FIN_DDR_AWLOCK),
    .AWCACHE(m_axi_FIN_DDR_AWCACHE),
    .AWPROT(m_axi_FIN_DDR_AWPROT),
    .AWQOS(m_axi_FIN_DDR_AWQOS),
    .AWREGION(m_axi_FIN_DDR_AWREGION),
    .AWUSER(m_axi_FIN_DDR_AWUSER),
    .WVALID(m_axi_FIN_DDR_WVALID),
    .WREADY(m_axi_FIN_DDR_WREADY),
    .WDATA(m_axi_FIN_DDR_WDATA),
    .WSTRB(m_axi_FIN_DDR_WSTRB),
    .WLAST(m_axi_FIN_DDR_WLAST),
    .WID(m_axi_FIN_DDR_WID),
    .WUSER(m_axi_FIN_DDR_WUSER),
    .ARVALID(m_axi_FIN_DDR_ARVALID),
    .ARREADY(m_axi_FIN_DDR_ARREADY),
    .ARADDR(m_axi_FIN_DDR_ARADDR),
    .ARID(m_axi_FIN_DDR_ARID),
    .ARLEN(m_axi_FIN_DDR_ARLEN),
    .ARSIZE(m_axi_FIN_DDR_ARSIZE),
    .ARBURST(m_axi_FIN_DDR_ARBURST),
    .ARLOCK(m_axi_FIN_DDR_ARLOCK),
    .ARCACHE(m_axi_FIN_DDR_ARCACHE),
    .ARPROT(m_axi_FIN_DDR_ARPROT),
    .ARQOS(m_axi_FIN_DDR_ARQOS),
    .ARREGION(m_axi_FIN_DDR_ARREGION),
    .ARUSER(m_axi_FIN_DDR_ARUSER),
    .RVALID(m_axi_FIN_DDR_RVALID),
    .RREADY(m_axi_FIN_DDR_RREADY),
    .RDATA(m_axi_FIN_DDR_RDATA),
    .RLAST(m_axi_FIN_DDR_RLAST),
    .RID(m_axi_FIN_DDR_RID),
    .RUSER(m_axi_FIN_DDR_RUSER),
    .RRESP(m_axi_FIN_DDR_RRESP),
    .BVALID(m_axi_FIN_DDR_BVALID),
    .BREADY(m_axi_FIN_DDR_BREADY),
    .BRESP(m_axi_FIN_DDR_BRESP),
    .BID(m_axi_FIN_DDR_BID),
    .BUSER(m_axi_FIN_DDR_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(FIN_DDR_ARVALID),
    .I_ARREADY(FIN_DDR_ARREADY),
    .I_ARADDR(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARADDR),
    .I_ARID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARID),
    .I_ARLEN(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLEN),
    .I_ARSIZE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARSIZE),
    .I_ARLOCK(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLOCK),
    .I_ARCACHE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARCACHE),
    .I_ARQOS(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARQOS),
    .I_ARPROT(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARPROT),
    .I_ARUSER(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARUSER),
    .I_ARBURST(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARBURST),
    .I_ARREGION(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARREGION),
    .I_RVALID(FIN_DDR_RVALID),
    .I_RREADY(FIN_DDR_RREADY),
    .I_RDATA(FIN_DDR_RDATA),
    .I_RID(FIN_DDR_RID),
    .I_RUSER(FIN_DDR_RUSER),
    .I_RRESP(FIN_DDR_RRESP),
    .I_RLAST(FIN_DDR_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(FIN_DDR_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(FIN_DDR_WREADY),
    .I_WDATA(128'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(16'd0),
    .I_BVALID(FIN_DDR_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(FIN_DDR_BRESP),
    .I_BID(FIN_DDR_BID),
    .I_BUSER(FIN_DDR_BUSER)
);

cnna_FOUT_DDR_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 128 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_FOUT_DDR_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_FOUT_DDR_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_FOUT_DDR_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_FOUT_DDR_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_FOUT_DDR_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_FOUT_DDR_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_FOUT_DDR_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_FOUT_DDR_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_FOUT_DDR_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_FOUT_DDR_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_FOUT_DDR_CACHE_VALUE ))
cnna_FOUT_DDR_m_axi_U(
    .AWVALID(m_axi_FOUT_DDR_AWVALID),
    .AWREADY(m_axi_FOUT_DDR_AWREADY),
    .AWADDR(m_axi_FOUT_DDR_AWADDR),
    .AWID(m_axi_FOUT_DDR_AWID),
    .AWLEN(m_axi_FOUT_DDR_AWLEN),
    .AWSIZE(m_axi_FOUT_DDR_AWSIZE),
    .AWBURST(m_axi_FOUT_DDR_AWBURST),
    .AWLOCK(m_axi_FOUT_DDR_AWLOCK),
    .AWCACHE(m_axi_FOUT_DDR_AWCACHE),
    .AWPROT(m_axi_FOUT_DDR_AWPROT),
    .AWQOS(m_axi_FOUT_DDR_AWQOS),
    .AWREGION(m_axi_FOUT_DDR_AWREGION),
    .AWUSER(m_axi_FOUT_DDR_AWUSER),
    .WVALID(m_axi_FOUT_DDR_WVALID),
    .WREADY(m_axi_FOUT_DDR_WREADY),
    .WDATA(m_axi_FOUT_DDR_WDATA),
    .WSTRB(m_axi_FOUT_DDR_WSTRB),
    .WLAST(m_axi_FOUT_DDR_WLAST),
    .WID(m_axi_FOUT_DDR_WID),
    .WUSER(m_axi_FOUT_DDR_WUSER),
    .ARVALID(m_axi_FOUT_DDR_ARVALID),
    .ARREADY(m_axi_FOUT_DDR_ARREADY),
    .ARADDR(m_axi_FOUT_DDR_ARADDR),
    .ARID(m_axi_FOUT_DDR_ARID),
    .ARLEN(m_axi_FOUT_DDR_ARLEN),
    .ARSIZE(m_axi_FOUT_DDR_ARSIZE),
    .ARBURST(m_axi_FOUT_DDR_ARBURST),
    .ARLOCK(m_axi_FOUT_DDR_ARLOCK),
    .ARCACHE(m_axi_FOUT_DDR_ARCACHE),
    .ARPROT(m_axi_FOUT_DDR_ARPROT),
    .ARQOS(m_axi_FOUT_DDR_ARQOS),
    .ARREGION(m_axi_FOUT_DDR_ARREGION),
    .ARUSER(m_axi_FOUT_DDR_ARUSER),
    .RVALID(m_axi_FOUT_DDR_RVALID),
    .RREADY(m_axi_FOUT_DDR_RREADY),
    .RDATA(m_axi_FOUT_DDR_RDATA),
    .RLAST(m_axi_FOUT_DDR_RLAST),
    .RID(m_axi_FOUT_DDR_RID),
    .RUSER(m_axi_FOUT_DDR_RUSER),
    .RRESP(m_axi_FOUT_DDR_RRESP),
    .BVALID(m_axi_FOUT_DDR_BVALID),
    .BREADY(m_axi_FOUT_DDR_BREADY),
    .BRESP(m_axi_FOUT_DDR_BRESP),
    .BID(m_axi_FOUT_DDR_BID),
    .BUSER(m_axi_FOUT_DDR_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(FOUT_DDR_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(FOUT_DDR_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(FOUT_DDR_RDATA),
    .I_RID(FOUT_DDR_RID),
    .I_RUSER(FOUT_DDR_RUSER),
    .I_RRESP(FOUT_DDR_RRESP),
    .I_RLAST(FOUT_DDR_RLAST),
    .I_AWVALID(FOUT_DDR_AWVALID),
    .I_AWREADY(FOUT_DDR_AWREADY),
    .I_AWADDR(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWADDR),
    .I_AWID(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWID),
    .I_AWLEN(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLEN),
    .I_AWSIZE(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWSIZE),
    .I_AWLOCK(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLOCK),
    .I_AWCACHE(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWCACHE),
    .I_AWQOS(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWQOS),
    .I_AWPROT(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWPROT),
    .I_AWUSER(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWUSER),
    .I_AWBURST(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWBURST),
    .I_AWREGION(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWREGION),
    .I_WVALID(FOUT_DDR_WVALID),
    .I_WREADY(FOUT_DDR_WREADY),
    .I_WDATA(grp_testAxiProcess_fu_462_m_axi_foddr_V_WDATA),
    .I_WID(grp_testAxiProcess_fu_462_m_axi_foddr_V_WID),
    .I_WUSER(grp_testAxiProcess_fu_462_m_axi_foddr_V_WUSER),
    .I_WLAST(grp_testAxiProcess_fu_462_m_axi_foddr_V_WLAST),
    .I_WSTRB(grp_testAxiProcess_fu_462_m_axi_foddr_V_WSTRB),
    .I_BVALID(FOUT_DDR_BVALID),
    .I_BREADY(FOUT_DDR_BREADY),
    .I_BRESP(FOUT_DDR_BRESP),
    .I_BID(FOUT_DDR_BID),
    .I_BUSER(FOUT_DDR_BUSER)
);

testAxiProcess grp_testAxiProcess_fu_462(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_testAxiProcess_fu_462_ap_start),
    .ap_done(grp_testAxiProcess_fu_462_ap_done),
    .ap_idle(grp_testAxiProcess_fu_462_ap_idle),
    .ap_ready(grp_testAxiProcess_fu_462_ap_ready),
    .cnn_iPara_width_read(cnnInst_iPara_width_reg_571),
    .cnn_iPara_height_read(cnnInst_iPara_height_reg_576),
    .cnn_iPara_ciAlign_V_read(cnnInst_iPara_ciAlig_reg_581),
    .cnn_iPara_memAddrImgIn_V_read(cnnInst_iPara_memAdd_reg_586),
    .cnn_oPara_coAlign_V_read(cnnInst_oPara_coAlig_reg_611),
    .cnn_oPara_memAddrImgOut_V_read(cnnInst_oPara_memAdd_reg_591),
    .m_axi_fiddr_V_AWVALID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWVALID),
    .m_axi_fiddr_V_AWREADY(1'b0),
    .m_axi_fiddr_V_AWADDR(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWADDR),
    .m_axi_fiddr_V_AWID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWID),
    .m_axi_fiddr_V_AWLEN(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWLEN),
    .m_axi_fiddr_V_AWSIZE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWSIZE),
    .m_axi_fiddr_V_AWBURST(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWBURST),
    .m_axi_fiddr_V_AWLOCK(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWLOCK),
    .m_axi_fiddr_V_AWCACHE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWCACHE),
    .m_axi_fiddr_V_AWPROT(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWPROT),
    .m_axi_fiddr_V_AWQOS(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWQOS),
    .m_axi_fiddr_V_AWREGION(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWREGION),
    .m_axi_fiddr_V_AWUSER(grp_testAxiProcess_fu_462_m_axi_fiddr_V_AWUSER),
    .m_axi_fiddr_V_WVALID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WVALID),
    .m_axi_fiddr_V_WREADY(1'b0),
    .m_axi_fiddr_V_WDATA(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WDATA),
    .m_axi_fiddr_V_WSTRB(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WSTRB),
    .m_axi_fiddr_V_WLAST(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WLAST),
    .m_axi_fiddr_V_WID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WID),
    .m_axi_fiddr_V_WUSER(grp_testAxiProcess_fu_462_m_axi_fiddr_V_WUSER),
    .m_axi_fiddr_V_ARVALID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARVALID),
    .m_axi_fiddr_V_ARREADY(FIN_DDR_ARREADY),
    .m_axi_fiddr_V_ARADDR(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARADDR),
    .m_axi_fiddr_V_ARID(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARID),
    .m_axi_fiddr_V_ARLEN(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLEN),
    .m_axi_fiddr_V_ARSIZE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARSIZE),
    .m_axi_fiddr_V_ARBURST(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARBURST),
    .m_axi_fiddr_V_ARLOCK(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARLOCK),
    .m_axi_fiddr_V_ARCACHE(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARCACHE),
    .m_axi_fiddr_V_ARPROT(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARPROT),
    .m_axi_fiddr_V_ARQOS(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARQOS),
    .m_axi_fiddr_V_ARREGION(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARREGION),
    .m_axi_fiddr_V_ARUSER(grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARUSER),
    .m_axi_fiddr_V_RVALID(FIN_DDR_RVALID),
    .m_axi_fiddr_V_RREADY(grp_testAxiProcess_fu_462_m_axi_fiddr_V_RREADY),
    .m_axi_fiddr_V_RDATA(FIN_DDR_RDATA),
    .m_axi_fiddr_V_RLAST(FIN_DDR_RLAST),
    .m_axi_fiddr_V_RID(FIN_DDR_RID),
    .m_axi_fiddr_V_RUSER(FIN_DDR_RUSER),
    .m_axi_fiddr_V_RRESP(FIN_DDR_RRESP),
    .m_axi_fiddr_V_BVALID(1'b0),
    .m_axi_fiddr_V_BREADY(grp_testAxiProcess_fu_462_m_axi_fiddr_V_BREADY),
    .m_axi_fiddr_V_BRESP(2'd0),
    .m_axi_fiddr_V_BID(1'd0),
    .m_axi_fiddr_V_BUSER(1'd0),
    .fiddr_V_offset(fiddr_V3_reg_561),
    .m_axi_foddr_V_AWVALID(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWVALID),
    .m_axi_foddr_V_AWREADY(FOUT_DDR_AWREADY),
    .m_axi_foddr_V_AWADDR(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWADDR),
    .m_axi_foddr_V_AWID(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWID),
    .m_axi_foddr_V_AWLEN(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLEN),
    .m_axi_foddr_V_AWSIZE(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWSIZE),
    .m_axi_foddr_V_AWBURST(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWBURST),
    .m_axi_foddr_V_AWLOCK(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWLOCK),
    .m_axi_foddr_V_AWCACHE(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWCACHE),
    .m_axi_foddr_V_AWPROT(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWPROT),
    .m_axi_foddr_V_AWQOS(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWQOS),
    .m_axi_foddr_V_AWREGION(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWREGION),
    .m_axi_foddr_V_AWUSER(grp_testAxiProcess_fu_462_m_axi_foddr_V_AWUSER),
    .m_axi_foddr_V_WVALID(grp_testAxiProcess_fu_462_m_axi_foddr_V_WVALID),
    .m_axi_foddr_V_WREADY(FOUT_DDR_WREADY),
    .m_axi_foddr_V_WDATA(grp_testAxiProcess_fu_462_m_axi_foddr_V_WDATA),
    .m_axi_foddr_V_WSTRB(grp_testAxiProcess_fu_462_m_axi_foddr_V_WSTRB),
    .m_axi_foddr_V_WLAST(grp_testAxiProcess_fu_462_m_axi_foddr_V_WLAST),
    .m_axi_foddr_V_WID(grp_testAxiProcess_fu_462_m_axi_foddr_V_WID),
    .m_axi_foddr_V_WUSER(grp_testAxiProcess_fu_462_m_axi_foddr_V_WUSER),
    .m_axi_foddr_V_ARVALID(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARVALID),
    .m_axi_foddr_V_ARREADY(1'b0),
    .m_axi_foddr_V_ARADDR(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARADDR),
    .m_axi_foddr_V_ARID(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARID),
    .m_axi_foddr_V_ARLEN(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARLEN),
    .m_axi_foddr_V_ARSIZE(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARSIZE),
    .m_axi_foddr_V_ARBURST(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARBURST),
    .m_axi_foddr_V_ARLOCK(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARLOCK),
    .m_axi_foddr_V_ARCACHE(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARCACHE),
    .m_axi_foddr_V_ARPROT(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARPROT),
    .m_axi_foddr_V_ARQOS(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARQOS),
    .m_axi_foddr_V_ARREGION(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARREGION),
    .m_axi_foddr_V_ARUSER(grp_testAxiProcess_fu_462_m_axi_foddr_V_ARUSER),
    .m_axi_foddr_V_RVALID(1'b0),
    .m_axi_foddr_V_RREADY(grp_testAxiProcess_fu_462_m_axi_foddr_V_RREADY),
    .m_axi_foddr_V_RDATA(128'd0),
    .m_axi_foddr_V_RLAST(1'b0),
    .m_axi_foddr_V_RID(1'd0),
    .m_axi_foddr_V_RUSER(1'd0),
    .m_axi_foddr_V_RRESP(2'd0),
    .m_axi_foddr_V_BVALID(FOUT_DDR_BVALID),
    .m_axi_foddr_V_BREADY(grp_testAxiProcess_fu_462_m_axi_foddr_V_BREADY),
    .m_axi_foddr_V_BRESP(FOUT_DDR_BRESP),
    .m_axi_foddr_V_BID(FOUT_DDR_BID),
    .m_axi_foddr_V_BUSER(FOUT_DDR_BUSER),
    .foddr_V_offset(foddr_V5_reg_556),
    .bbuf0_V_address0(grp_testAxiProcess_fu_462_bbuf0_V_address0),
    .bbuf0_V_ce0(grp_testAxiProcess_fu_462_bbuf0_V_ce0),
    .bbuf0_V_q0(bbuf0_V_q0)
);

loadBiasFromDRAM grp_loadBiasFromDRAM_fu_482(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_loadBiasFromDRAM_fu_482_ap_start),
    .ap_done(grp_loadBiasFromDRAM_fu_482_ap_done),
    .ap_idle(grp_loadBiasFromDRAM_fu_482_ap_idle),
    .ap_ready(grp_loadBiasFromDRAM_fu_482_ap_ready),
    .cnn_oParaNext_co_V_read(cnnInst_oParaNext_co_reg_596),
    .cnn_wParaNext_memAddrBias_V_read(cnnInst_wParaNext_me_reg_601),
    .m_axi_SHARED_DRAM_V_AWVALID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWVALID),
    .m_axi_SHARED_DRAM_V_AWREADY(1'b0),
    .m_axi_SHARED_DRAM_V_AWADDR(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWADDR),
    .m_axi_SHARED_DRAM_V_AWID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWID),
    .m_axi_SHARED_DRAM_V_AWLEN(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWLEN),
    .m_axi_SHARED_DRAM_V_AWSIZE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWSIZE),
    .m_axi_SHARED_DRAM_V_AWBURST(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWBURST),
    .m_axi_SHARED_DRAM_V_AWLOCK(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWLOCK),
    .m_axi_SHARED_DRAM_V_AWCACHE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWCACHE),
    .m_axi_SHARED_DRAM_V_AWPROT(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWPROT),
    .m_axi_SHARED_DRAM_V_AWQOS(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWQOS),
    .m_axi_SHARED_DRAM_V_AWREGION(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWREGION),
    .m_axi_SHARED_DRAM_V_AWUSER(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_AWUSER),
    .m_axi_SHARED_DRAM_V_WVALID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WVALID),
    .m_axi_SHARED_DRAM_V_WREADY(1'b0),
    .m_axi_SHARED_DRAM_V_WDATA(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WDATA),
    .m_axi_SHARED_DRAM_V_WSTRB(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WSTRB),
    .m_axi_SHARED_DRAM_V_WLAST(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WLAST),
    .m_axi_SHARED_DRAM_V_WID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WID),
    .m_axi_SHARED_DRAM_V_WUSER(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_WUSER),
    .m_axi_SHARED_DRAM_V_ARVALID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARVALID),
    .m_axi_SHARED_DRAM_V_ARREADY(WEIGHTS_DDR_ARREADY),
    .m_axi_SHARED_DRAM_V_ARADDR(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARADDR),
    .m_axi_SHARED_DRAM_V_ARID(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARID),
    .m_axi_SHARED_DRAM_V_ARLEN(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLEN),
    .m_axi_SHARED_DRAM_V_ARSIZE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARSIZE),
    .m_axi_SHARED_DRAM_V_ARBURST(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARBURST),
    .m_axi_SHARED_DRAM_V_ARLOCK(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARLOCK),
    .m_axi_SHARED_DRAM_V_ARCACHE(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARCACHE),
    .m_axi_SHARED_DRAM_V_ARPROT(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARPROT),
    .m_axi_SHARED_DRAM_V_ARQOS(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARQOS),
    .m_axi_SHARED_DRAM_V_ARREGION(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARREGION),
    .m_axi_SHARED_DRAM_V_ARUSER(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARUSER),
    .m_axi_SHARED_DRAM_V_RVALID(WEIGHTS_DDR_RVALID),
    .m_axi_SHARED_DRAM_V_RREADY(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_RREADY),
    .m_axi_SHARED_DRAM_V_RDATA(WEIGHTS_DDR_RDATA),
    .m_axi_SHARED_DRAM_V_RLAST(WEIGHTS_DDR_RLAST),
    .m_axi_SHARED_DRAM_V_RID(WEIGHTS_DDR_RID),
    .m_axi_SHARED_DRAM_V_RUSER(WEIGHTS_DDR_RUSER),
    .m_axi_SHARED_DRAM_V_RRESP(WEIGHTS_DDR_RRESP),
    .m_axi_SHARED_DRAM_V_BVALID(1'b0),
    .m_axi_SHARED_DRAM_V_BREADY(grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_BREADY),
    .m_axi_SHARED_DRAM_V_BRESP(2'd0),
    .m_axi_SHARED_DRAM_V_BID(1'd0),
    .m_axi_SHARED_DRAM_V_BUSER(1'd0),
    .SHARED_DRAM_V_offset(wddr_V1_reg_566),
    .bbuf_V_address0(grp_loadBiasFromDRAM_fu_482_bbuf_V_address0),
    .bbuf_V_ce0(grp_loadBiasFromDRAM_fu_482_bbuf_V_ce0),
    .bbuf_V_we0(grp_loadBiasFromDRAM_fu_482_bbuf_V_we0),
    .bbuf_V_d0(grp_loadBiasFromDRAM_fu_482_bbuf_V_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_loadBiasFromDRAM_fu_482_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_loadBiasFromDRAM_fu_482_ap_start_reg <= 1'b1;
        end else if ((grp_loadBiasFromDRAM_fu_482_ap_ready == 1'b1)) begin
            grp_loadBiasFromDRAM_fu_482_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_testAxiProcess_fu_462_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_testAxiProcess_fu_462_ap_start_reg <= 1'b1;
        end else if ((grp_testAxiProcess_fu_462_ap_ready == 1'b1)) begin
            grp_testAxiProcess_fu_462_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cnnInst_iPara_ciAlig_reg_581 <= layer_iPara_ciAlign_V_0_data_reg;
        cnnInst_iPara_height_reg_576 <= layer_iPara_height_0_data_reg;
        cnnInst_iPara_memAdd_reg_586 <= layer_iPara_memAddrImgIn_V_0_data_reg;
        cnnInst_iPara_width_reg_571 <= layer_iPara_width_0_data_reg;
        cnnInst_oParaNext_co_reg_596 <= layer_oParaNext_co_V_0_data_reg;
        cnnInst_oPara_memAdd_reg_591 <= layer_oPara_memAddrImgOut_V_0_data_reg;
        cnnInst_wParaNext_me_reg_601 <= layer_wParaNext_memAddrBias_V_0_data_reg;
        fiddr_V3_reg_561 <= {{fiddr_V_0_data_reg[31:4]}};
        foddr_V5_reg_556 <= {{foddr_V_0_data_reg[31:4]}};
        tmp_3_reg_606 <= {{ret_V_1_tr_fu_532_p2[12:5]}};
        wddr_V1_reg_566 <= {{wddr_V_0_data_reg[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cnnInst_oPara_coAlig_reg_611[12 : 5] <= cnnInst_oPara_coAlig_fu_548_p3[12 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (fiddr_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (fiddr_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (fiddr_V_0_vld_reg == 1'b1)))) begin
        fiddr_V_0_data_reg <= fiddr_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (foddr_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (foddr_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (foddr_V_0_vld_reg == 1'b1)))) begin
        foddr_V_0_data_reg <= foddr_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_ciAlign_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_ciAlign_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_iPara_ciAlign_V_0_vld_reg == 1'b1)))) begin
        layer_iPara_ciAlign_V_0_data_reg <= layer_iPara_ciAlign_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_height_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_height_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_iPara_height_0_vld_reg == 1'b1)))) begin
        layer_iPara_height_0_data_reg <= layer_iPara_height;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_memAddrImgIn_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_memAddrImgIn_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_iPara_memAddrImgIn_V_0_vld_reg == 1'b1)))) begin
        layer_iPara_memAddrImgIn_V_0_data_reg <= layer_iPara_memAddrImgIn_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_width_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_iPara_width_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_iPara_width_0_vld_reg == 1'b1)))) begin
        layer_iPara_width_0_data_reg <= layer_iPara_width;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oParaNext_co_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oParaNext_co_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_oParaNext_co_V_0_vld_reg == 1'b1)))) begin
        layer_oParaNext_co_V_0_data_reg <= layer_oParaNext_co_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oPara_co_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oPara_co_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_oPara_co_V_0_vld_reg == 1'b1)))) begin
        layer_oPara_co_V_0_data_reg <= layer_oPara_co_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oPara_memAddrImgOut_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_oPara_memAddrImgOut_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_oPara_memAddrImgOut_V_0_vld_reg == 1'b1)))) begin
        layer_oPara_memAddrImgOut_V_0_data_reg <= layer_oPara_memAddrImgOut_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_wParaNext_memAddrBias_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (layer_wParaNext_memAddrBias_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (layer_wParaNext_memAddrBias_V_0_vld_reg == 1'b1)))) begin
        layer_wParaNext_memAddrBias_V_0_data_reg <= layer_wParaNext_memAddrBias_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (wddr_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (wddr_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (wddr_V_0_vld_reg == 1'b1)))) begin
        wddr_V_0_data_reg <= wddr_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        FIN_DDR_ARVALID = grp_testAxiProcess_fu_462_m_axi_fiddr_V_ARVALID;
    end else begin
        FIN_DDR_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        FIN_DDR_RREADY = grp_testAxiProcess_fu_462_m_axi_fiddr_V_RREADY;
    end else begin
        FIN_DDR_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        FOUT_DDR_AWVALID = grp_testAxiProcess_fu_462_m_axi_foddr_V_AWVALID;
    end else begin
        FOUT_DDR_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        FOUT_DDR_BREADY = grp_testAxiProcess_fu_462_m_axi_foddr_V_BREADY;
    end else begin
        FOUT_DDR_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        FOUT_DDR_WVALID = grp_testAxiProcess_fu_462_m_axi_foddr_V_WVALID;
    end else begin
        FOUT_DDR_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        WEIGHTS_DDR_ARVALID = grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_ARVALID;
    end else begin
        WEIGHTS_DDR_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        WEIGHTS_DDR_RREADY = grp_loadBiasFromDRAM_fu_482_m_axi_SHARED_DRAM_V_RREADY;
    end else begin
        WEIGHTS_DDR_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bbuf0_V_address0 = grp_loadBiasFromDRAM_fu_482_bbuf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bbuf0_V_address0 = grp_testAxiProcess_fu_462_bbuf0_V_address0;
    end else begin
        bbuf0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bbuf0_V_ce0 = grp_loadBiasFromDRAM_fu_482_bbuf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bbuf0_V_ce0 = grp_testAxiProcess_fu_462_bbuf0_V_ce0;
    end else begin
        bbuf0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bbuf0_V_we0 = grp_loadBiasFromDRAM_fu_482_bbuf_V_we0;
    end else begin
        bbuf0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        fiddr_V_0_ack_out = 1'b1;
    end else begin
        fiddr_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        foddr_V_0_ack_out = 1'b1;
    end else begin
        foddr_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_iPara_ciAlign_V_0_ack_out = 1'b1;
    end else begin
        layer_iPara_ciAlign_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_iPara_height_0_ack_out = 1'b1;
    end else begin
        layer_iPara_height_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_iPara_memAddrImgIn_V_0_ack_out = 1'b1;
    end else begin
        layer_iPara_memAddrImgIn_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_iPara_width_0_ack_out = 1'b1;
    end else begin
        layer_iPara_width_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_oParaNext_co_V_0_ack_out = 1'b1;
    end else begin
        layer_oParaNext_co_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_oPara_co_V_0_ack_out = 1'b1;
    end else begin
        layer_oPara_co_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_oPara_memAddrImgOut_V_0_ack_out = 1'b1;
    end else begin
        layer_oPara_memAddrImgOut_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_wParaNext_memAddrBias_V_0_ack_out = 1'b1;
    end else begin
        layer_wParaNext_memAddrBias_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        wddr_V_0_ack_out = 1'b1;
    end else begin
        wddr_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_loadBiasFromDRAM_fu_482_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_testAxiProcess_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cnnInst_oPara_coAlig_fu_548_p3 = {{tmp_3_reg_606}, {5'd0}};

assign grp_loadBiasFromDRAM_fu_482_ap_start = grp_loadBiasFromDRAM_fu_482_ap_start_reg;

assign grp_testAxiProcess_fu_462_ap_start = grp_testAxiProcess_fu_462_ap_start_reg;

assign lhs_V_cast_fu_528_p1 = layer_oPara_co_V_0_data_reg;

assign ret_V_1_tr_fu_532_p2 = (lhs_V_cast_fu_528_p1 + 14'd31);

always @ (posedge ap_clk) begin
    cnnInst_oPara_coAlig_reg_611[4:0] <= 5'b00000;
end

endmodule //cnna
